workflows:
  compilacion-gratuita:
    name: Compilacion Android y Web
    environment:
      flutter: stable
    scripts:
      - name: Instalar dependencias
        script: flutter pub get
      - name: Compilar Android APK
        script: flutter build apk --release
      - name: Compilar Web
        script: flutter build web --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/web/**