// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6OmM7clK__uOGQgxhe-asAJlolWCAm-o',
    appId: '1:343437321688:web:622012eb61e71836dbbead',
    messagingSenderId: '343437321688',
    projectId: 'appi-dedca',
    authDomain: 'appi-dedca.firebaseapp.com',
    storageBucket: 'appi-dedca.firebasestorage.app',
    measurementId: 'G-MEVL83L11Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6bTr71qXPAQKX91KUtBatW8EtsNQxQVI',
    appId: '1:343437321688:android:6bf57b4ecd7e5a6bdbbead',
    messagingSenderId: '343437321688',
    projectId: 'appi-dedca',
    storageBucket: 'appi-dedca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0ixbrnsHH2VqIXhiU49dVT5KqAVKJnVQ',
    appId: '1:343437321688:ios:3aa12b1914bf9a71dbbead',
    messagingSenderId: '343437321688',
    projectId: 'appi-dedca',
    storageBucket: 'appi-dedca.firebasestorage.app',
    iosBundleId: 'com.example.fr024Iluminancia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0ixbrnsHH2VqIXhiU49dVT5KqAVKJnVQ',
    appId: '1:343437321688:ios:3aa12b1914bf9a71dbbead',
    messagingSenderId: '343437321688',
    projectId: 'appi-dedca',
    storageBucket: 'appi-dedca.firebasestorage.app',
    iosBundleId: 'com.example.fr024Iluminancia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6OmM7clK__uOGQgxhe-asAJlolWCAm-o',
    appId: '1:343437321688:web:5765b98fd9b4e809dbbead',
    messagingSenderId: '343437321688',
    projectId: 'appi-dedca',
    authDomain: 'appi-dedca.firebaseapp.com',
    storageBucket: 'appi-dedca.firebasestorage.app',
    measurementId: 'G-9LEYXLP8B7',
  );
}
